import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './styles.css'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
interface LayoutProps {
  children: React.ReactNode
}

export default function Layout({ children }: LayoutProps): React.ReactElement {
  return (
    <html lang="en" className="bg-indigo-500 text-white">
      <head></head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
